# Generated by Django 2.2.7 on 2020-06-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50)),
                ('companyid', models.CharField(max_length=50)),
                ('num', models.CharField(max_length=50)),
                ('jobname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('cash', models.CharField(max_length=50)),
            ],
        ),
    ]
